default: &default
  adapter: postgresql
  endoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *default
  database: ck_development

test:
  <<: *default
  database: ck_test

production:
  <<: *default
  database: ck_production
