From nginx

ENV WEB_ROOT /var/www/ck

WORKDIR $WEB_ROOT

RUN mkdir log

COPY public public/
COPY config/containers/nginx.conf /tmp/nginx.conf

RUN envsubst '$WEB_ROOT' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
